name: FloatingText
version: 1.0.1
main: FloatingText\Main
api: 5.0.0
author: ZyberPE

commands:
  ft:
    description: Floating text commands
    usage: /ft
    permission: floatingtext.command

permissions:
  floatingtext.command:
    default: op
